/*
  BARALHO OFICIAL EM PORTUGUES
  ----------------------------
  Traducao das 600 cartas do baralho oficial do Cards Against Humanity
  (versao 2.4), na mesma ordem do arquivo cartas.js.

  Cards Against Humanity e distribuido sob a licenca
  Creative Commons BY-NC-SA 2.0.
  https://creativecommons.org/licenses/by-nc-sa/2.0/

  A licenca permite traduzir, desde que se de credito e nao se venda.

  Algumas cartas citam marcas e programas de TV que nao existem no Brasil.
  Nesses casos ficou a descricao ("a lanchonete", "o programa da tarde"),
  senao a piada nao fecharia pra quem esta lendo.

  PRETAS  = as frases. O "___" e o espaco em branco.
  BRANCAS = as respostas.
*/

const PRETAS = [
  "Fala, Reddit! Eu sou ___. Pode perguntar o que quiser.",
  "Chegou o Beisebol Radical! É igual beisebol, mas com ___!",
  "Qual é o prazer culposo do Batman?",
  "As novas regras do aeroporto proíbem ___ dentro do avião.",
  "O novo da J.K. Rowling: Harry Potter e a Câmara de ___.",
  "Isso mesmo, eu matei ___. Como, você pergunta? ___.",
  "Desculpa, professor, mas eu não consegui fazer a lição por causa de ___.",
  "E o Oscar de ___ vai para ___.",
  "Cara, não entra nesse banheiro. Tem ___ lá dentro.",
  "Como eu perdi a virgindade?",
  "É uma pena que a molecada de hoje só se envolve com ___.",
  "Passo 1: ___. Passo 2: ___. Passo 3: Lucro.",
  "___. Aposto que você não consegue comer só um!",
  "Crianças, eu não preciso de droga pra ficar doidão. Eu me amarro em ___.",
  "No meu próximo truque, eu vou tirar ___ de dentro de ___.",
  "O senador não consegue gozar sem ___.",
  "No novo filme original do Disney Channel, a Hannah Montana enfrenta ___ pela primeira vez.",
  "Qual é o meu poder secreto?",
  "Essa semana eu vou desintoxicar. Só suco de couve e ___.",
  "___ + ___ = ___.",
  "Como o Faraó não se abalou, Moisés invocou uma praga de ___.",
  "Só uma vez eu queria te ouvir dizer \"Valeu, mãe. Valeu por ___.\"",
  "Papai, por que a mamãe está chorando?",
  "Quando eu estava viajando no ácido, ___ virou ___.",
  "Metade dos casamentos termina em ___.",
  "Meus compatriotas: antes do fim desta década, nós teremos ___ na Lua!",
  "Nesta temporada, o clássico existencial de Samuel Beckett: Esperando ___.",
  "Em vez de carvão, o Papai Noel agora dá pras crianças malcriadas ___.",
  "A vida dos índios mudou pra sempre quando o homem branco apresentou a eles ___.",
  "O que a ONG está usando pra inspirar os alunos da periferia a vencer na vida?",
  "Talvez ela já tenha nascido assim. Talvez seja ___.",
  "Meu nome é Peter Parker. Fui picado por uma aranha radioativa, e agora eu sou ___.",
  "Branco gosta de ___.",
  "___ é uma ladeira escorregadia que termina em ___.",
  "Por que está doendo tudo em mim?",
  "Um jantar romântico à luz de velas ficaria incompleto sem ___.",
  "Acabei de ver esse vídeo revoltante! Compartilhem, por favor!! #fora___",
  "Dica quente! Quando ele pedir sexo oral, surpreenda ele com ___.",
  "O passeio da escola foi completamente arruinado por ___.",
  "Qual é o melhor amigo de uma mulher?",
  "Querida Dra. Ana, estou tendo problemas com ___ e queria um conselho.",
  "No novo suspense do Jordan Peele, uma família descobre que ___ era ___ o tempo todo.",
  "Quando eu for presidente, vou criar o Ministério de ___.",
  "O que os meus pais escondem de mim?",
  "O que nunca falha em animar a festa?",
  "SE você curte ___, VOCÊ PODE SER UM CAIPIRA.",
  "Faça um haicai.",
  "O que deixou o meu primeiro beijo tão constrangedor?",
  "Oi, pessoal, bem-vindos ao restaurante! Que tal começar a noite com ___?",
  "Eu tenho 99 problemas, mas ___ não é um deles.",
  "___. É uma armadilha!",
  "O novo reality tem doze solteiros gatos morando com ___.",
  "O que a vovó acharia perturbador, mas estranhamente charmoso?",
  "___. Isso foi muito metal.",
  "Eu nunca entendi de verdade ___ até topar com ___.",
  "Durante o sexo, eu gosto de pensar em ___.",
  "O que acabou com o meu último relacionamento?",
  "Que barulho é esse?",
  "Ei, gente, eu sei que a ideia foi minha, mas estou com sérias dúvidas sobre ___.",
  "Por que eu estou grudento?",
  "Não sou médico, mas tenho quase certeza de que o que você tem se chama \"___.\"",
  "O que tem aos montes no céu?",
  "Depois de quatro discos de platina e três Grammys, é hora de voltar às minhas raízes, ao que me inspirou a fazer música: ___.",
  "O que sempre garante uma transa?",
  "Disseram que a gente era louco. Disseram que a gente não conseguiria botar ___ dentro de ___. Estavam errados.",
  "O canal apresenta: \"___: a História de ___.\"",
  "___: testado por crianças, aprovado pelas mães.",
  "Por que eu não consigo dormir à noite?",
  "Que cheiro é esse?",
  "Por que o Brett está tão suado?",
  "É assim que o mundo acaba / É assim que o mundo acaba / Não com um estrondo, mas com ___.",
  "Estreia nos teatros nesta temporada, ___: O Musical.",
  "Esta é a igreja / Esta é a torre / Abra as portas / E lá está ___.",
  "Mas antes de te matar, Sr. Bond, eu preciso te mostrar ___.",
  "Um estudo recente mostra que universitários transam 50% menos depois de serem expostos a ___.",
  "Chegou a incrível dupla de herói e ajudante! São ___ e ___!",
  "A seguir no canal de esportes: o Mundial de ___.",
  "Quando eu for bilionário, vou erguer uma estátua de quinze metros pra homenagear ___.",
  "Os historiadores militares lembram de Alexandre, o Grande, pelo uso brilhante de ___ contra os persas.",
  "Guerra! Pra que serve isso?",
  "O que me dá gases incontroláveis?",
  "A nova picape. Com potência e espaço pra levar ___ pra todo lugar.",
  "Bom, com licença, senhores, eu tenho um encontro com ___.",
  "A medicina alternativa agora abraçou os poderes curativos de ___.",
  "Como mãe de cinco meninos levados, eu já estou acostumada com ___.",
  "___. Toca aqui, irmão.",
  "Hoje no programa da tarde: \"Socorro! Meu filho é ___!\"",
  "Eu me viro com uma ajudinha de ___.",
  "NÃO venham aqui! Achei ___ no meu macarrão!",
  "Eu bebo pra esquecer ___.",
  "Eu sou o LeBron James, e quando não estou enterrando bola, eu amo ___.",
  "O que faz a vida valer a pena?",
  "A lanchonete: A Gente Tem ___.",
  "Sr. e Sra. Dias, chamamos vocês porque estamos preocupados com a Cíntia. Vocês sabiam que a filha de vocês é ___?",
  "Se você não pode ficar com quem você ama, ame ___.",
  "Oferecimento da cervejaria, a Cerveja Oficial de ___.",
  "Clique Aqui para ___!!!",
  "Olha só, mano! Eu chamo esse passo de \"___.\"",
  "Seu Lobato tinha ___. Ia ia ô.",
  "Loja de ternos: Você vai gostar de ___. Eu garanto."
];

const BRANCAS = [
  "Silêncio.",
  "A ilusão de escolha numa sociedade capitalista tardia.",
  "Muitos morcegos.",
  "Asiáticos gatos.",
  "Vergonha.",
  "Um site.",
  "Agredir um policial.",
  "Ímãs.",
  "Um pai de araque.",
  "Ver o que acontece quando você tranca gente numa sala com gaivotas famintas.",
  "Uma crucificação.",
  "Um dedo-duro.",
  "Frango à passarinho sem osso.",
  "Uma plateia ao vivo.",
  "Reclamar.",
  "Comida mexicana de verdade.",
  "Cometer crimes.",
  "A COVID-19.",
  "Uma dívida esmagadora.",
  "Trauma com o pai.",
  "Trabalhar num galpão da Amazon.",
  "Um pum tão potente que acorda os gigantes do sono de mil anos.",
  "O ex-presidente George W. Bush.",
  "Nudez frontal completa.",
  "Me cobrir de queijo ralado e pimenta porque eu sou uma pizza.",
  "Botar um ovo.",
  "Ficar pelado assistindo desenho.",
  "Fingir que se importa.",
  "Ter sonhos grandes e nenhum jeito realista de realizar.",
  "Ver a vovó pelada.",
  "Meleca.",
  "A bandeira confederada.",
  "O milagre do parto.",
  "Uma atitude positiva!",
  "Ter um derrame.",
  "O privilégio branco.",
  "Emergir do mar e destruir Tóquio.",
  "O ladrão de hambúrguer.",
  "O absorvente interno da minha vagina.",
  "O Sangue de Cristo.",
  "Sexo papai-e-mamãe, com beijinho.",
  "BATMAN!",
  "A agricultura.",
  "Ganhar uma miséria por ano.",
  "A seleção natural.",
  "Os coroas.",
  "Soltar um cocô quente pelo buraco de trás.",
  "Meu namorado agressivo que até que não é tão ruim quando você conhece.",
  "Analgésico tarja preta.",
  "Dar o bote.",
  "Homem explicando o óbvio.",
  "Uma montagem homoerótica de vôlei.",
  "A deputada mais nova do congresso.",
  "Botar as coisas no lugar.",
  "Segurar um moedor de pimenta sem motivo nenhum.",
  "Dar à luz na cadeia.",
  "Um velho quase morrendo.",
  "O Kanye West.",
  "Queijo quente.",
  "Ser morto por um serial killer.",
  "Sete mortos e três em estado grave.",
  "Esmegma.",
  "O alcoolismo.",
  "Um coroa de patins.",
  "Ninguém dando a mínima pra nada.",
  "Agarrar meu homem pelos pneuzinhos e comer aquele bundão.",
  "Entupir meu buraco do xixi de bala.",
  "Ódio de si mesmo.",
  "Sentar na minha cara e dizer que eu sou um lixo.",
  "Preliminares feitas nas coxas.",
  "A Bíblia Sagrada.",
  "Pornô alemão de masmorra.",
  "Estar pegando fogo.",
  "Usar humor pra não surtar.",
  "O Gandhi.",
  "Seu irmão esquisito.",
  "Anticoncepcional.",
  "Coisa nojenta, tipo doentia mesmo.",
  "Uma ereção de mais de quatro horas.",
  "Um ménage com a minha esposa e o Shaquille O'Neal.",
  "O passado.",
  "Meus genitais.",
  "Um jato infinito de diarreia.",
  "A ciência.",
  "Não retribuir o sexo oral.",
  "Aves que não voam.",
  "Uma boa cheirada.",
  "Cinquenta mil volts direto nos mamilos.",
  "A balada.",
  "Passarinho morto pra todo lado.",
  "A chegada da pizza.",
  "Síndrome da Cara de Orgasmo Permanente.",
  "O sabor gelado e refrescante do refrigerante.",
  "Síndrome do intestino irritável.",
  "A apresentadora de televisão.",
  "Ficar pensando se dá pra levar um pouco daquele molho pra viagem.",
  "Bananas.",
  "Vergonha alheia.",
  "Meus peitim.",
  "Trocar de seguradora.",
  "Fazer xixi um pouquinho.",
  "Sonho molhado.",
  "Os judeus.",
  "Meu marido safado e traidor.",
  "Coxas poderosas.",
  "Essas vagabundas.",
  "A única pessoa gay num raio de cem quilômetros.",
  "Transar pela primeira vez.",
  "O ex-presidente.",
  "Beijar a vovó na testa e desligar os aparelhos.",
  "Um certo não sei quê.",
  "Um fuzil de assalto.",
  "Meu sutiã bom.",
  "Dar um soco na cara de um deputado.",
  "Dizer que está tudo bem quando claramente não está.",
  "Ser rico.",
  "Boiando no rio junto com o resto do lixo.",
  "Os políticos de direita.",
  "Cheirar e beijar os meus pés.",
  "Uma mulher bem mais nova.",
  "A pobreza.",
  "A vice-presidente.",
  "Cometer suicídio.",
  "Um perdedor igual você.",
  "Um erro.",
  "Esguichar.",
  "Música de mago.",
  "O mascote do suco em pó.",
  "Explicar a diferença entre sexo e gênero.",
  "Amostra grátis.",
  "Machucar quem está mais perto de mim.",
  "Dar morango na boca do meu piriguete.",
  "O acordo que contava escravo como três quintos de gente.",
  "Amamentação.",
  "Rir com taça de champanhe na mão enquanto os pobres morrem de frio lá fora.",
  "Calar a boca pra eu poder ver o jogo.",
  "Comer um ovo cozido de dentro do cu do meu marido.",
  "Fazer coisa de branco com um bando de branco.",
  "Um peito de fora.",
  "Comer todos os amigos do meu pai.",
  "Beber gasolina só pra ver o gosto.",
  "Cantoria inapropriada.",
  "A puberdade.",
  "Fantasmas.",
  "Cinquenta miligramas de antidepressivo por dia.",
  "Comer a minha irmã.",
  "Trançar três pintos e fazer uma bala de goma.",
  "Mãozinha de jazz bem entusiasmada.",
  "Levar dedo.",
  "O meu motorista de aplicativo, o Pavel.",
  "Iogurte de tubinho.",
  "Violência policial.",
  "Um aborto.",
  "Pré-adolescentes.",
  "Minha filha gorda.",
  "Água potável.",
  "Sumir aos poucos até virar nada.",
  "O Darth Vader.",
  "Uma punheta triste.",
  "Exatamente o que você esperava.",
  "A teoria racial crítica.",
  "Remédio pra déficit de atenção.",
  "A sua mãe.",
  "O peito de lado aparecendo.",
  "Um polvo dando sete punhetas e fumando um cigarro.",
  "Meu pescoço, minhas costas, minha xota e meu rego.",
  "O júri e seus associados.",
  "Herpes na boca.",
  "Cachalotes.",
  "Mulheres negras.",
  "Homens conversando sobre sentimentos de um jeito emocionalmente saudável.",
  "Incesto.",
  "O Pac-Man engolindo porra sem parar.",
  "Sugerir um ménage como quem não quer nada.",
  "Ficar sem esperma.",
  "Deus.",
  "Dar ré em cima de uma criança com o carro.",
  "Mijar na minha boca sedenta.",
  "Emoções.",
  "Lamber as coisas pra marcar que são suas.",
  "Empregos.",
  "A placenta.",
  "Uma boca que suga o cromo de uma maçaneta.",
  "A final do reality de namoro.",
  "Jogar uva num homem até ele perder o contato com a realidade.",
  "Estabelecer domínio.",
  "Pintura com o dedo.",
  "Cheiro de velho.",
  "Ser esmagado por uma máquina de refrigerante.",
  "Meus demônios internos.",
  "Uma pistola d'água cheia de xixi de gato.",
  "A calda de panqueca com a marca racista.",
  "Ficar de conchinha.",
  "Toda a maconha que vinte reais compra.",
  "Amputações no campo de batalha.",
  "Macarrão? De novo?",
  "O Ronald Reagan.",
  "Uma festa de aniversário decepcionante.",
  "Nachos pra mesa.",
  "Virar um mirtilo.",
  "Um cavalinho.",
  "Caranguejo.",
  "Vender crack pra criança.",
  "O sanduíche de frango picante da lanchonete.",
  "Os pardos.",
  "Nerds da banda da escola que transam muito.",
  "Pedófilos.",
  "Fungo.",
  "O quanto a minha filha estragou a apresentação de dança dela.",
  "Retângulos.",
  "Ser uma bosta de pessoa.",
  "Os pobres.",
  "Só namorar mulher asiática.",
  "Botar criança em jaula.",
  "A madame que quer falar com o gerente.",
  "Como é bom estar de cogumelo.",
  "Julgar todo mundo.",
  "Um júri só de brancos.",
  "Casar, ter uns filhos, comprar umas coisas, se aposentar na praia e morrer.",
  "Um puto de um sossego.",
  "AIDS.",
  "Fotos de peito.",
  "Personagens femininas fortes.",
  "Ser decapitado por um helicóptero.",
  "Cuidados paliativos.",
  "Ficar muito doidão.",
  "A epidemia de opioides.",
  "Inveja do pênis.",
  "Terapia de reversão sexual.",
  "Hambúrguer e buceta.",
  "Cheirar a porra.",
  "A Ku Klux Klan.",
  "Um polvo pangênero que vagueia pelo cosmos em busca de amor.",
  "Metanfetamina.",
  "Cianeto.",
  "Segurar uma criança e peidar em cima dela.",
  "Um brinquedo de apertar botão.",
  "Um tijolo inteiro de manteiga.",
  "Ainda ser virgem.",
  "Resolver os problemas na porrada.",
  "Levar gozada em cima.",
  "Bukkake pixelado.",
  "Uma vida inteira de tristeza.",
  "Um acordo de confidencialidade.",
  "Foto de pau.",
  "Racismo.",
  "Fúria menstrual.",
  "Sol e arco-íris.",
  "O presidente americano.",
  "Noventa gramas de urina limpa.",
  "Usar droga com os meus filhos.",
  "Meu melhor amigo gay.",
  "Um jato fininho de gozo que brilha no ar da manhã.",
  "Executar um refém por hora.",
  "Os ritmos da África.",
  "Sair cantando e dançando do nada.",
  "Lepra.",
  "Buraco de sacanagem no banheiro público.",
  "Lâminas nos mamilos.",
  "O coração de uma criança.",
  "Filhotinhos!",
  "Comunhão com Cristo.",
  "Minha esposa transando com a sua esposa.",
  "Acordar meio pelado no estacionamento de uma lanchonete.",
  "Uma mulher mais velha que sabe o que fazer com um pau.",
  "Tirar a droga da rua e botar dentro do meu corpo.",
  "O cuzinho delicioso do Daniel Radcliffe.",
  "Escuta ativa.",
  "Limpeza étnica.",
  "Buceta coçando.",
  "Chupar meu namorado com tanta força que ele se caga.",
  "Uma tonelada de amêndoas.",
  "Um homem cis fazendo papel de mulher trans.",
  "Esperar até o casamento.",
  "NFTs.",
  "Fingir que é dentista.",
  "O Diabo em pessoa.",
  "A salvação.",
  "Disfunção erétil.",
  "Minha coleção de brinquedos sexuais japoneses.",
  "O Papa.",
  "Os brancos.",
  "Pornô de tentáculo.",
  "Meu buraco rosa-choque.",
  "Até onde eu consigo enfiar o meu próprio pau na minha bunda.",
  "Ter ânus no lugar dos olhos.",
  "Dois calmantes e uma garrafa de vinho.",
  "Minha escorpião de estimação, a Tina.",
  "O Danny DeVito.",
  "A magia do teatro ao vivo.",
  "Jogar uma virgem dentro do vulcão.",
  "O Dwayne \"The Rock\" Johnson.",
  "Aceitar as coisas como elas são.",
  "O astro da NBA LeBron James.",
  "Ouvir os problemas dela sem tentar resolver.",
  "Terapia.",
  "Ser gordo e burro.",
  "Cagar pra frente e pra trás. Pra sempre.",
  "Rasgar aquela bunda igual papel de presente na manhã de Natal.",
  "Mais pinto de elefante do que eu esperava.",
  "Uma surpresa salgada.",
  "O interior do país.",
  "A violação dos nossos direitos mais básicos.",
  "Dinheiro do petróleo saudita.",
  "Sexo consensual.",
  "Contar uma história de merda que não leva a lugar nenhum.",
  "Um gorila bom e forte.",
  "Ver meu pai chorar.",
  "Necrofilia.",
  "Ser mulher.",
  "Se meter num acidente de carro bem feio.",
  "O cientista da televisão.",
  "Os negros.",
  "Estimulação da próstata.",
  "Aquele kit de lanche pronto.",
  "Vadias.",
  "Um moleque folgado que roubou o meu sanduíche.",
  "Órfãos adoráveis.",
  "A companhia aérea mais barata.",
  "Passivos de bunda empinada.",
  "Uma tigela de maionese com dentes humanos.",
  "Cocô ardido.",
  "Dizer \"eu te amo\".",
  "Enfiar um pote de vidro no meu ânus.",
  "O verdadeiro sentido do Natal.",
  "O que tiver na geladeira.",
  "Ser dono de uma franquia de restaurante.",
  "Estrogênio.",
  "Meninas.",
  "Os russos.",
  "Um cu clareado.",
  "Comer o homem do tempo ao vivo na televisão.",
  "Estresse pós-traumático.",
  "Forças obscuras e misteriosas além do nosso controle.",
  "Cobertores com varíola.",
  "Bater punheta.",
  "Moradores de rua.",
  "Peidar pela buceta.",
  "Meu escravo sexual, o Reginaldo.",
  "A Cardi B.",
  "Viagra.",
  "Sopa quente demais.",
  "O menino mais feio da cidade.",
  "Explicar como funciona a vagina.",
  "A atriz vencedora do Oscar Meryl Streep.",
  "Beber sozinho.",
  "Dedos em forma de pinto.",
  "Vários golpes de faca.",
  "A pena de morte.",
  "Uma mão de apoio na lombar.",
  "Bolinhas anais.",
  "Massacrar civis inocentes.",
  "Tirar antes de gozar.",
  "Conseguir conversar com elefantes.",
  "Carne de cavalo.",
  "Um chapéu muito maneiro.",
  "O Stalin.",
  "Um pelo pubiano perdido.",
  "Adorar aquela buceta.",
  "Uma confiança completamente injustificada.",
  "Dar pelo cu.",
  "Minha ex-mulher.",
  "Peitinhos que fazem \"iupi!\" quando você encosta.",
  "Encostar bem no pinto de um pug.",
  "Um moinho cheio de cadáveres.",
  "O pacote completo.",
  "O Vladimir Putin.",
  "O Patriarcado.",
  "O teto de vidro.",
  "Vomitar frutos do mar e sangrar pelo cu.",
  "O Sonho Americano.",
  "Não usar calça.",
  "Meu saco na sua cara.",
  "Cagar dentro de um notebook e fechar.",
  "Uma vadia qualquer que gosta de abacaxi.",
  "Prepúcio.",
  "Ser esmagado entre as coxas da Serena Williams.",
  "Italianos.",
  "Um feto.",
  "Dar tiro pro alto enquanto come um porco que grita.",
  "Gás natural.",
  "Mais de dez mil imigrantes.",
  "Masculinidade tóxica.",
  "Meu status de relacionamento.",
  "Uma gravidez indesejada.",
  "a marvel",
  "Meu chefe.",
  "Abelhas?",
  "Pornô do Harry Potter.",
  "Dar à luz ao Anticristo.",
  "Três paus ao mesmo tempo.",
  "Nazistas.",
  "Duzentos gramas de heroína mexicana.",
  "O que essa boca faz.",
  "Pais mortos.",
  "Permanência do objeto.",
  "Polegares opositores.",
  "Questões de vestibular racialmente enviesadas.",
  "A Grande Depressão.",
  "Motosserra no lugar das mãos.",
  "O Nicolas Cage.",
  "Tipo, sei lá.",
  "Explosões.",
  "Não vacinar meus filhos porque eu sou burro.",
  "Nosso consolo.",
  "Cheirar tinta spray.",
  "Um homem à beira do orgasmo.",
  "Usar camisinha.",
  "Invadir a Polônia.",
  "Minha vagina.",
  "Calça de cowboy sem a parte da bunda.",
  "Assassinato.",
  "Tomar chá de kombucha com cara de esnobe.",
  "Sua Majestade, a Rainha Elizabeth II.",
  "Jesus negro.",
  "Memes.",
  "Sexo com animais.",
  "Ser marginalizado.",
  "Duendes.",
  "Esperança.",
  "Os políticos de esquerda.",
  "Um micropênis.",
  "Cometer traição.",
  "Uma bola de cera de ouvido, esperma e unha cortada.",
  "Uma horda de vikings.",
  "Gente bonita.",
  "Ferver de raiva calada.",
  "Complexo de Édipo.",
  "Gansos.",
  "Calça apertada demais.",
  "O jornal sensacionalista.",
  "Um garotinho que não cala a boca sobre dinossauro.",
  "O Bryan Cranston, logo ele.",
  "Atropelar e matar.",
  "O voto feminino.",
  "Um cara qualquer.",
  "A juíza do programa de televisão.",
  "Subir num poste e virar um com a rede de telefonia.",
  "O massacre desse mês.",
  "O Barack Obama.",
  "Imigrantes ilegais.",
  "Meu filho tarado.",
  "O orgasmo feminino.",
  "Heteronormatividade.",
  "Farelo espalhado por todo o tapete.",
  "As grandes corporações.",
  "A senha do wi-fi.",
  "Um general chinês viajante do tempo da dinastia Shang.",
  "Um passarinho que caga cocô de gente.",
  "Um leão deprimido do zoológico.",
  "Manifestantes contra o aborto.",
  "Escolhas ruins na vida.",
  "Minha vida sexual.",
  "Auschwitz.",
  "Cocaína no almoço.",
  "Todos os caras que eu já comi.",
  "O clitóris.",
  "O Big Bang.",
  "Minas terrestres.",
  "O coral inteiro da igreja.",
  "Um miniporco de capinha de chuva e botinha.",
  "Bafo de pinto.",
  "Vício em jogo.",
  "Carne de homem.",
  "Um tempo pra mim.",
  "A rota de fuga dos escravos.",
  "Fazer canoagem com as minhas vadias.",
  "Sacudir meu troço.",
  "Fantasia de lenhador.",
  "Bode.",
  "Mulheres de propaganda de iogurte.",
  "Implorar literalmente pra morrer.",
  "Ser um puta de um feiticeiro.",
  "Minha bunda preta.",
  "Conexão humana genuína.",
  "Anunciar que estou prestes a gozar.",
  "Bolas.",
  "A vovó.",
  "Fricção.",
  "Passar pomada no pinto infeccionado do meu avô.",
  "Peidar e sair andando.",
  "Ser babaca com criança.",
  "Um trilhão de reais.",
  "Afogar as crianças na banheira.",
  "Morrer.",
  "Beber água da privada e comer lixo.",
  "Os gays.",
  "Os gritos... os gritos horríveis.",
  "Homens.",
  "O bombardeio de Nagasaki.",
  "Peito de silicone.",
  "Os amish.",
  "Chamar a polícia por causa de um homem negro inocente.",
  "Minha cara feia e minha personalidade ruim.",
  "Um tapa na cara.",
  "Um tumor no cérebro.",
  "Dar risadinha igual menina de anime.",
  "Bunda suada.",
  "O leiteiro.",
  "Cartas Contra a Humanidade."
];

module.exports = { PRETAS, BRANCAS };
