/*
  BARALHO EM PORTUGUES
  --------------------
  Estas cartas NAO sao traducao do baralho oficial: sao originais, escritas
  pra fazer sentido com humor brasileiro (fila de banco, grupo da familia,
  boleto, tia do pave). Traduzir as 600 do oficial daria outra coisa, e
  muita piada de la nao funciona aqui.

  PRETAS  = as frases. O "___" e o espaco em branco.
            Duas ou tres marcas "___" na mesma frase = jogue 2 ou 3 cartas.
  BRANCAS = as respostas.

  Quer somar as suas proprias cartas? Escreva mais linhas nas listas.
*/

const PRETAS = [
  "Qual é o segredo do meu sucesso? ___.",
  "Nunca subestime o poder de ___.",
  "O que acabou com o meu relacionamento? ___.",
  "Cuidado com ___. Não perdoa ninguém.",
  "No meu tempo livre eu pratico ___.",
  "A nova regra da empresa proíbe ___ no horário de trabalho.",
  "Meu terapeuta disse que eu preciso parar com ___.",
  "___: a nova sensação do TikTok.",
  "Depois de ___, nada mais faz sentido.",
  "O que eu escondo debaixo da cama? ___.",
  "Trouxe ___ pro amigo secreto.",
  "Foi aberta uma CPI para investigar ___.",
  "O que me faz chorar no banho? ___.",
  "Bem-vindo ao inferno. Aqui só tem ___.",
  "___? No Brasil isso é normal.",
  "Meu plano infalível pra ficar rico: ___.",
  "A missa de domingo foi cancelada por causa de ___.",
  "Perdi meu emprego por causa de ___.",
  "O que a minha sogra acha do meu casamento? ___.",
  "Primeiro veio ___, depois veio ___.",
  "Troquei ___ por ___ e me arrependo até hoje.",
  "No churrasco da família nunca pode faltar ___.",
  "Descobri tarde demais que ___ não combina com ___.",
  "A verdadeira causa do aquecimento global é ___.",
  "___ me traumatizou pra sempre.",
  "Como eu passei de ano? ___.",
  "O grupo da família no WhatsApp só fala sobre ___.",
  "___. Foi assim que a humanidade acabou.",
  "Minha última mensagem antes de morrer: ___.",
  "O que tem dentro da caixa misteriosa? ___.",
  "Novo reality show: dez pessoas trancadas numa casa com ___.",
  "Meu perfil no app de namoro diz que eu gosto de ___.",
  "A polícia me parou por causa de ___.",
  "Só existem duas coisas que eu odeio: ___ e ___.",
  "Eu prefiro ___ do que ___.",
  "___: recomendado por nove em cada dez dentistas.",
  "O que eu faço quando ninguém está olhando? ___.",
  "Fui expulso do grupo por causa de ___.",
  "O motivo do meu atraso foi ___.",
  "Nada aquece mais o coração do que ___.",
  "A pior parte de ser adulto é ___.",
  "Meu superpoder secreto é ___.",
  "Nunca mais vou olhar pra ___ do mesmo jeito.",
  "O que os professores fazem na sala dos professores? ___.",
  "___ é o novo ___.",
  "Eu seria capaz de matar por ___.",
  "Meu pai saiu pra comprar cigarro e voltou com ___.",
  "Na minha lápide vai estar escrito: ___.",
  "Segundo a ciência, ___ causa ___.",
  "O que é pior do que um vizinho barulhento? ___.",
  "Eu não durmo direito desde que vi ___.",
  "Fala, galera do canal! Hoje a gente vai falar sobre ___.",
  "Vovó, o que é isso? ___.",
  "O Brasil seria um país melhor sem ___.",
  "Encontrei ___ no meu histórico de busca.",
  "Não existe amor mais puro do que o amor por ___.",
  "___? Só se for agora!",
  "Meu pior encontro envolveu ___ e ___.",
  "Pra que o cachorro tanto latia? ___.",
  "Nunca conte pra ninguém sobre ___.",
  "A herança do meu avô foi ___.",
  "O que eu levaria pra uma ilha deserta? ___.",
  "Faltou ___ no meu casamento.",
  "Meu chefe me chamou na sala pra falar sobre ___.",
  "___ não é problema, é solução.",
  "O último desejo do condenado foi ___.",
  "Novo sabor de salgadinho: ___.",
  "Estou em terapia por causa de ___.",
  "Tudo que eu queria era ___, mas a vida me deu ___.",
  "Consegui uma bolsa de estudos estudando ___.",
  "O que a inteligência artificial vai dominar primeiro? ___.",
  "Prefiro nem contar o que aconteceu com ___.",
  "A pandemia acabou, mas ficou ___.",
  "Meu maior arrependimento: ___.",
  "O apocalipse vai começar com ___ e terminar com ___."
];

const BRANCAS = [
  "Um pastel de vento",
  "Chorar no banheiro do trabalho",
  "A conta de luz",
  "Meu ex",
  "Um boleto vencido",
  "A tia do pavê",
  "O silêncio constrangedor",
  "Dançar sozinho no quarto",
  "Um copo de água quente",
  "Falar sozinho no espelho",
  "Uma dívida no cartão",
  "O grupo da família",
  "Um pombo agressivo",
  "Fingir que entendeu a piada",
  "Meia furada",
  "O último pedaço de pizza",
  "Um abraço apertado demais",
  "A crise dos 30",
  "Cair da escada em público",
  "Um áudio de sete minutos",
  "Pedir desculpa sem motivo",
  "O cheiro do ônibus lotado",
  "Trabalho de segunda-feira",
  "Um bolo de fubá",
  "Rir na hora errada",
  "A sogra chegando de surpresa",
  "Ficar sem internet",
  "Um pé descalço no lego",
  "O visto e não respondido",
  "Uma unha encravada",
  "Correr do cachorro do vizinho",
  "Beijar de olho aberto",
  "Chamar a professora de mãe",
  "Café requentado",
  "Um estagiário desesperado",
  "Passar vergonha na frente do crush",
  "Ligar pra própria mãe chorando",
  "Um cochilo de quatro horas",
  "A conta do bar",
  "Perder o último ônibus",
  "Fofoca de condomínio",
  "Um churrasco na chuva",
  "Falar mal do chefe no grupo errado",
  "O barulho do vizinho às 3 da manhã",
  "Um crush que não responde",
  "Suor frio",
  "Uma dança do TikTok",
  "Encarar o teto às 4 da manhã",
  "A pressão social",
  "Um bilhete anônimo",
  "Terapia em grupo",
  "O motoboy atrasado",
  "Segunda opinião médica",
  "Um susto no escuro",
  "Coçar as costas com a régua",
  "Cabelo no sabonete",
  "O gato do vizinho me julgando",
  "Uma promessa quebrada",
  "Karaokê às 6 da manhã",
  "Enviar mensagem pro contato errado",
  "Um plano infalível que falhou",
  "Fingir estar doente",
  "Aquele amigo que some",
  "A fila do banco",
  "Um miojo mal cozido",
  "Meu currículo",
  "A academia que eu paguei e nunca fui",
  "O boleto do IPTU",
  "Uma discussão às três da manhã",
  "Chorar por causa de um comercial",
  "A senha que eu esqueci",
  "Meu histórico do navegador",
  "Um espirro alto demais",
  "Ganhar de presente uma meia",
  "Falar com sotaque falso",
  "Um pedido de desculpa por áudio",
  "Descobrir a verdade sem querer",
  "O tio bêbado do Natal",
  "Cinco horas de trânsito",
  "Um sanduíche esquecido na mochila",
  "Dormir de calça jeans",
  "A internet do interior",
  "Errar o nome da pessoa",
  "Uma live às 2 da manhã",
  "Um post apagado às pressas",
  "O cheiro de shopping",
  "Meu saldo bancário",
  "Um conselho não pedido",
  "Cortar o cabelo sozinho",
  "Rir de nervoso na hora errada",
  "Uma reunião que podia ser um e-mail",
  "O barulho do estômago no silêncio",
  "A tosse na hora da prova",
  "Um vídeo de gato",
  "Segurar o espirro",
  "Fazer amizade com o entregador",
  "Uma foto ruim no documento",
  "Perder a chave de casa",
  "O trabalho em grupo da faculdade",
  "Um sonho muito estranho",
  "Falar dormindo",
  "A tarefa que eu deixei pra última hora",
  "Um bicho no travesseiro",
  "Ficar preso no elevador",
  "Aquela lembrança que volta do nada",
  "Meu primeiro e-mail",
  "Um encontro às escuras",
  "Duzentos reais na mão errada",
  "Coragem líquida",
  "O sofá da sala",
  "Um plano de saúde negado",
  "Chegar cedo demais na festa",
  "Sair sem se despedir",
  "Uma amizade colorida",
  "Um bolo caído",
  "Beber leite vencido",
  "A galinha do vizinho",
  "Um pum silencioso",
  "Confundir sal com açúcar",
  "O último dia de férias",
  "Um professor substituto",
  "Vergonha alheia",
  "Um segredo mal guardado",
  "O cheiro de chuva",
  "O Papai Noel do shopping",
  "Uma pegadinha que deu errado",
  "Ficar sem bateria",
  "O amigo que só aparece pra pedir favor",
  "Um pedido de pizza sem queijo",
  "Ver o próprio vídeo antigo",
  "Meia-noite e a geladeira",
  "Uma piada que ninguém entendeu",
  "Passar a noite acordado",
  "Um curso online abandonado",
  "Uma vaquinha na internet",
  "O botão de soneca",
  "Ganhar na loteria e perder o bilhete",
  "Uma tatuagem escrita errado",
  "Falar inglês no chuveiro",
  "Um susto no espelho",
  "A cadeira que range",
  "Meu grupo de amigos",
  "Chorar assistindo desenho",
  "Um cachorro que fala",
  "A verdade nua e crua",
  "Levar bolo",
  "Um discurso de casamento",
  "Encontrar dinheiro no bolso",
  "Perder o Wi-Fi na hora boa",
  "Trocar de time no meio do jogo",
  "Um vizinho que reforma aos domingos",
  "A luz do celular no escuro",
  "Um trote de madrugada",
  "Ficar com fome de madrugada",
  "Sentar em chiclete",
  "Uma apresentação sem slides",
  "Fingir estar ocupado",
  "Meu pior boletim",
  "Um copo quebrado na festa",
  "Ler o contrato inteiro",
  "Uma mentira inocente",
  "Falar demais numa entrevista",
  "Ficar preso na leitura do termo de uso",
  "Uma escada rolante parada",
  "Passar mal no parque de diversões",
  "O gosto de remédio",
  "Um cheque sem fundo",
  "Escolher o filme errado",
  "Andar de bicicleta sem freio",
  "Um karaokê desafinado",
  "Perder a aposta",
  "Um bilhete na geladeira",
  "Ficar de castigo aos trinta anos",
  "O motorista de aplicativo falante",
  "Um pedido de emprego negado",
  "A vergonha de pedir ajuda",
  "Ver a conta do restaurante",
  "Uma dieta que durou dois dias",
  "Amanhã eu começo",
  "Um treino de perna",
  "Levar pisão no pé",
  "Rir sem motivo na aula",
  "O último episódio",
  "Um recomeço",
  "Uma revelação inesperada",
  "Um vizinho na janela",
  "Ficar sem papel higiênico",
  "O barulho do despertador",
  "Meu talento inútil",
  "A conta dividida errada",
  "Uma multa de trânsito",
  "Ficar preso no banheiro",
  "Um elogio forçado",
  "Explicar meme pros pais",
  "Uma foto marcada sem permissão",
  "Ganhar abraço de quem eu não gosto",
  "O suspense antes do resultado",
  "Uma promessa de campanha",
  "Um copo de suco derramado no teclado",
  "Falar besteira na frente do chefe",
  "Sonhar acordado",
  "Comer o último bombom da caixa",
  "Uma amizade de infância",
  "Ficar no vácuo",
  "Um cochilo na reunião",
  "Aquele barulho estranho do carro",
  "Cantar em português no chuveiro",
  "Uma vaga que pede dez anos de experiência",
  "Um bebê chorando no avião",
  "Ganhar o primeiro salário",
  "Um encontro com o passado",
  "Meu eu de dezesseis anos",
  "Um roteiro de viagem impossível",
  "O último dia do prazo",
  "Uma cadeira de plástico quebrando",
  "Ficar sem palavras",
  "Uma indireta muito direta",
  "Sorrir pra foto sem querer",
  "Beber café de estômago vazio",
  "Um plano B",
  "Chegar em casa de madrugada",
  "Ficar com sono depois do almoço",
  "Meu apelido da escola",
  "Uma corrida atrás do ônibus",
  "O silêncio do grupo depois da piada",
  "Um alarme de incêndio às 5 da manhã",
  "Um gol contra",
  "A pressão de escolher o restaurante",
  "Ver a própria letra de criança",
  "Um casaco que some no inverno",
  "O peso da responsabilidade",
  "Um sorvete que cai da casquinha",
  "A vontade de sumir",
  "Uma segunda chance"
];

module.exports = { PRETAS, BRANCAS };
